// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // docs: [
  //   'introduction',
  //   {
  //     type: 'category',
  //     label: 'Getting Started',
  //     link: {
  //       type: 'generated-index',
  //     },
  //     collapsed: false,
  //     items: [
  //       'installation',
  //       'configuration',
  //       'playground',
  //       'typescript-support',
  //     ],
  //   },

  // But you can create a sidebar manually
  Documentation: [
    'intro',
    // 'introduction/features_ngenue',
    {
      type: 'doc',
      id: 'introduction/features_ngenue',
      label: 'Key functionalities',
    },
    {
      type: 'doc',
      id: 'testimonials',
      label: 'Testimonials',
    },
    {
      type: 'category',
      // id: 'installation_guide/overview',
      label: 'Installation guide',
      link: {
        type: 'doc',
        id: 'installation_guide/overview', // this will open when clicking the category
      },
        items: [
          {
            type: 'doc',
            id: 'installation_guide/system_requirements',
            label: 'System Requirements',
          },
          'installation_guide/sql_server_installation',
          {
            type: 'doc',
            id: 'installation_guide/restore_database',
            label: 'Restore Database',
          },
          'installation_guide/run_ngenue_application',
          {
            type: 'doc',
            id: 'installation_guide/post_installation/ssrs_configure',
            label: 'SSRS configuration',
          },
          {
            type: 'doc',
            id: 'installation_guide/post_installation/edi_configure',
            label: 'EDI configuration',
          },
        ], 
      }, 
      {
        type: 'doc',
        id: 'faqs/overview',
        label: 'FAQs',
      },  
      {
        type: 'doc',
        id: 'glossary/index',
        label: 'Glossary',
      },  
  ],

  EDI: [  
    {
      type: 'category',
      label: 'EDI',
      collapsed: false,
      items: ['edi/overview'],
    },
  ],

  ETRM: [    
    {
      type: 'category',
      label: 'ETRM',
      collapsed: false,
      items: ['etrm/overview'],
    },
  ],
  PQE: [      
    {
      type: 'category',
      label: 'PQE',
      collapsed: false,
      items: ['pqe/overview'],
    },
  ],
  Retail: [    
    {
      type: 'category',
      label: 'Retail',
      collapsed: false,
      items: ['retail/overview'],
    },
  ],
};

export default sidebars;
